apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configuration
  labels:
    app: redis
data:
  master.conf: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data