apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-172-26-7-114
      initContainers:
      - name: init-redis
        image: redis:latest
        command:
          - bash
          - "-c"
          - |
              cp /mnt/master.conf /etc/redis-config.conf
        volumeMounts:
          - name: redis-claim
            mountPath: /etc
          - name: config-map
            mountPath: /mnt/
      containers:
      - name: redis
        image: redis:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - "/etc/redis-config.conf"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-claim
          mountPath: /etc
      volumes:
      - name: config-map
        configMap:
          name: redis-configuration
      - name: redis-data
        emptyDir:
          medium: ""
          sizeLimit: 1Gi
      - name: redis-claim
        emptyDir:
          medium: ""
          sizeLimit: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-03
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-172-26-7-114
      securityContext:
        runAsUser: 1001
      containers:
      - name: web
        image: findnull45/web-vote-app:latest
        env:
        - name: WEB_VOTE_NUMBER
          value: "03"
        securityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080