apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: "/data/db"
---
apiVersion: v1
kind: PeersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_PASSWORD: cGc4Njc1MzA5
stringData:
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgresdb
data:
  POSTGRES_DB: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:9.4.26
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-configmap
        volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: db-data
    volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-persistent-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: store
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP 
      port: 5432