apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: result-app
        image: findnull45/result-app:latest
        securityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  selector:
    app: result-app
  ports:
  - port: 8080

