apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
spec:
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
        node: worker0
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: vote-worker
        image: findnull45/vote-worker:latest
        env:
        - name: FROM_REDIS_HOST
          value: "1"
        - name: TO_REDIS_HOST
          value: "3"
        - name: WORKER_NUMBER
          value: '01'
        securityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "2000m"