controller:
  config:
    load-balance: ewma
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodeUsedFor
            operator: In
            values:
            - ingress
  replicaCount: 3
